# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96c95897679768bd9fd0a1c46c58a1c6cff56a7108f777cb1e7d84a321fd2893ec3cee8935d3a93943bd7b4bfa4453022dcbbcdaa02a0f012bb1bbaf38d7a866

test:
  secret_key_base: ca9f89a60884c3c825a13a101fcb27d9eb99f5e9a2c0515bce0c76c3ea8d0b1568d724b77cce368d0547efbfca8b41356c4ce58ea4ac386a44c925a1afbfe44d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
